
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class LoginDetail extends javax.swing.JFrame  implements InterfaceA,InterfaceB{

    /**
     * Creates new form LoginDetail
     */
    DbConnectivity db;
      
    String [] data;
    
    public LoginDetail() {
        initComponents(); 
        
        db=DbConnectivity.getobject();
        jPanel6.setBackground(new Color(0,0,0,10));
        jPanel7.setBackground(new Color(0,0,0,10));
        jPanel3.setBackground(new Color(0,0,0,10));
        //combo1.setBackground(Color.BLACK);
       // BackButton1.setBackground(Color.BLACK);
        //this.currentUser();
       this.logindata();
       currentuser.setText(db.retrievecurrentuser());
       
        
    }
    
    JframeFactory jf=new JframeFactory();
    
    public void x()
    {
       this.setVisible(true);
    }
    public void back()
    {
        this.setVisible(true);
    }

  public boolean search( String searchtype,String searchby)
    {
        
        boolean found=false;
        db=DbConnectivity.getobject();
        Connection con=db.DbConnection();
        DefaultTableModel tm1=(DefaultTableModel)jTable1.getModel();
               while(tm1.getRowCount()> 0)
               {
                tm1.removeRow(0);
               }
               if(searchtype.equals("Date"))
        {

            //searchby=searchbar.getText();

            try{
                String regnum=db.currentuserregnum();
                System.out.println(regnum);
                Statement stmt=con.createStatement();
               ResultSet rs=stmt.executeQuery("select date,time,ipaddress from loginDetail where username='"+db.currentusername+"' and date='"+searchby+"'");
            
            int i=0;
            while(rs.next()){
                found=true;
               String id=String.valueOf(i+1);
               String date=rs.getString("date");
               String time=rs.getString("time");
               String ipaddress=rs.getString("ipaddress");
               
               
               String tbtable[]={id,date,time,ipaddress};
               data=tbtable;
               DefaultTableModel tm2=(DefaultTableModel)jTable1.getModel();
               
               tm2.addRow(data);
               i++;
                }

            }
            catch(Exception e){
            }

        }

        else if(searchtype.equals("Time"))//time
        {
            try{
                String regnum=db.currentuserregnum();
                System.out.println(regnum);
                Statement stmt=con.createStatement();
               ResultSet rs=stmt.executeQuery("select date,time,ipaddress from loginDetail where username='"+db.currentusername+"'and time='"+searchby+"'");
            
            int i=0;
            while(rs.next()){
                found=true;
               String id=String.valueOf(i+1);
               String date=rs.getString("date");
               String time=rs.getString("time");
               String ipaddress=rs.getString("ipaddress");
               
               
               String tbtable[]={id,date,time,ipaddress};
               data=tbtable;
               DefaultTableModel tm2=(DefaultTableModel)jTable1.getModel();
               
               tm2.addRow(data);
               i++;
            }

            }
            catch(Exception e){
            }

        }
        else
        {
            try{
                String regnum=db.currentuserregnum();
                System.out.println(regnum);
                Statement stmt=con.createStatement();
               ResultSet rs=stmt.executeQuery("select date,time,ipaddress from loginDetail where username='"+db.currentusername+"'and ipaddress='"+searchby+"'");
            
            int i=0;
            while(rs.next()){
                found=true;
               String id=String.valueOf(i+1);
               String date=rs.getString("date");
               String time=rs.getString("time");
               String ipaddress=rs.getString("ipaddress");
               
               
               String tbtable[]={id,date,time,ipaddress};
               data=tbtable;
               DefaultTableModel tm2=(DefaultTableModel)jTable1.getModel();
               
               tm2.addRow(data);
               i++;
            }

            }
            catch(Exception e){
            }
        }
               
               
     return found;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        BackButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        currentuser = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        SearchComboBox1 = new javax.swing.JComboBox<>();
        searchbar = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        BackButton.setText("BACK");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addGap(52, 52, 52))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton1.setText("BACK");
        BackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(BackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 90, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FAUX Ticket Reservation");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 30));

        currentuser.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        currentuser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.add(currentuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 10, 80, 20));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(730, 339));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Account Details");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Login");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 123, -1));

        combo1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Login", "Payment", "Reservation", "Personal" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        jPanel6.add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 130, -1));

        SearchComboBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        SearchComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Date", "Time", "IPaddress" }));
        jPanel6.add(SearchComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 20, 130, -1));

        searchbar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchbar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbarActionPerformed(evt);
            }
        });
        jPanel6.add(searchbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 120, -1));

        searchbutton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });
        jPanel6.add(searchbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("NEED HELP!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 60, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 65, 940, 110));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel7.setText("Serial #");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 66, -1));

        jLabel9.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel9.setText("Date");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 66, -1));

        jLabel10.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel10.setText("IP address");
        jPanel7.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel11.setText("Time");
        jPanel7.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 66, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 940, 40));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "", "", ""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 900, 190));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 247, 940, 240));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resize invitación.jpeg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 510));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        
        InterfaceB ua=jf.getObject2("useraccount");
        ua.back();
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void BackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton1ActionPerformed
        // TODO add your handling code here:
        InterfaceB ua=jf.getObject2("useraccount");
        ua.back();
        this.dispose();
    }//GEN-LAST:event_BackButton1ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
        if(combo1.getSelectedItem().equals("Login"))
        {
            InterfaceA c1=jf.getObject("login");
            c1.x();
            this.dispose();
        }
        else if(combo1.getSelectedItem().equals("Payment"))
        {
            InterfaceA c2=jf.getObject("payment");
            c2.x();
            this.dispose();
        }
        else if(combo1.getSelectedItem().equals("Reservation"))
        {
            InterfaceA c3=jf.getObject("reservation");
            c3.x();
            this.dispose();
        }else
        {
            PersonalDetails p=new PersonalDetails();
            p.setVisible(true);
            this.dispose();
        }
        
    }//GEN-LAST:event_combo1ActionPerformed

    private void searchbarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchbarActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:
       String searchtype;
String searchby;
        if(SearchComboBox1.getSelectedItem().equals("Date"))
        {
            searchtype="Date";
        }

        else if(SearchComboBox1.getSelectedItem().equals("Time"))//time
        {
           searchtype="Time";
        }
        else
        {
            searchtype="IPaddress";
        }
        
        searchby=searchbar.getText();
       boolean found=search(searchtype,searchby);
       if(found)
       {
           JOptionPane.showMessageDialog(null,"Search is Successfull");
       }
       else
       {
           JOptionPane.showMessageDialog(null,"NO such data exist");
       }
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        chatbox2 c=new chatbox2();
        c.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

        public boolean logindata()
    {
        DbConnectivity db;
        db=DbConnectivity.getobject();
        boolean found=false;
        Connection con=db.DbConnection();
 
 try{
           String regnum=db.currentuserregnum();
           System.out.println(regnum);
            Statement stmt=con.createStatement();
            ResultSet rs=stmt.executeQuery("select date,time,ipaddress from loginDetail where username='"+db.currentusername+"'");
            
            int i=0;
            while(rs.next()){
                found=true;
               String id=String.valueOf(i+1);
               String date=rs.getString("date");
               String time=rs.getString("time");
               String ipaddress=rs.getString("ipaddress");
               
               
               String tbtable[]={id,date,time,ipaddress};
               data=tbtable;
               DefaultTableModel tm1=(DefaultTableModel)jTable1.getModel();
               
               tm1.addRow(data);
               i++;
            }
            
        }
        catch(Exception e){
            
        }
 return found;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BackButton1;
    private javax.swing.JComboBox<String> SearchComboBox1;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JLabel currentuser;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField searchbar;
    private javax.swing.JButton searchbutton;
    // End of variables declaration//GEN-END:variables
}
