/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.Color;
/**
 *
 * @author itsna
 */
public class UserAccount extends javax.swing.JFrame implements InterfaceB {
//private ReservationDetails rd;
    /**
     * Creates new form UserAccount
     */
    DbConnectivity db;
    public UserAccount() {
        initComponents();
        jPanel5.setBackground(new Color(0,0,0,10));
        jPanel6.setBackground(new Color(0,0,0,10));
        //reservhistButton.setBackground(Color.BLACK);
        //loginhistbutton.setBackground(Color.BLACK);
        //PaymentHistButton.setBackground(Color.BLACK);
        //BackButton1.setBackground(Color.BLACK);
        
        db=DbConnectivity.getobject();
        currentuser.setText(db.retrievecurrentuser());
    }

public void back()
{
    this.setVisible(true);
}

public void currentuser()
{
    currentuser.setText("izma03");
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        reservhistButton = new javax.swing.JButton();
        loginhistbutton = new javax.swing.JButton();
        PaymentHistButton = new javax.swing.JButton();
        personal = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        BackButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        currentuser = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setForeground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        reservhistButton.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        reservhistButton.setForeground(new java.awt.Color(102, 102, 102));
        reservhistButton.setText("RESERVATION");
        reservhistButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reservhistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservhistButtonActionPerformed(evt);
            }
        });
        jPanel6.add(reservhistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 250, -1));

        loginhistbutton.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        loginhistbutton.setForeground(new java.awt.Color(102, 102, 102));
        loginhistbutton.setText("LOGIN");
        loginhistbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginhistbuttonActionPerformed(evt);
            }
        });
        jPanel6.add(loginhistbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 250, -1));

        PaymentHistButton.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        PaymentHistButton.setForeground(new java.awt.Color(102, 102, 102));
        PaymentHistButton.setText("PAYMENT");
        PaymentHistButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentHistButtonActionPerformed(evt);
            }
        });
        jPanel6.add(PaymentHistButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 240, -1));

        personal.setFont(new java.awt.Font("Sitka Display", 1, 24)); // NOI18N
        personal.setForeground(new java.awt.Color(102, 102, 102));
        personal.setText("PERSONAL DETAILS");
        personal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personalActionPerformed(evt);
            }
        });
        jPanel6.add(personal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 250, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 670, 370));

        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setOpaque(false);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Account Details");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, 40));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Menu");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 100, 40));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 420, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resize invitación.jpeg"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 570));

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton1.setBackground(new java.awt.Color(255, 255, 255));
        BackButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BackButton1.setText("BACK");
        BackButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(BackButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 90, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("FAUX Ticket Reservation");
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 210, 30));

        currentuser.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        currentuser.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.add(currentuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, 20));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reservhistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservhistButtonActionPerformed
        // TODO add your handling code here:
        JframeFactory jf=new JframeFactory();
        InterfaceA rd=jf.getObject("reservation");
        rd.x();
        this.dispose();
    }//GEN-LAST:event_reservhistButtonActionPerformed

    private void loginhistbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginhistbuttonActionPerformed
        // TODO add your handling code here:
        JframeFactory jf=new JframeFactory();
        InterfaceA ld=jf.getObject("login");
        //LoginDetail ld=new LoginDetail();
        ld.x();
        this.dispose();
    }//GEN-LAST:event_loginhistbuttonActionPerformed

    private void PaymentHistButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentHistButtonActionPerformed
        // TODO add your handling code here:
        JframeFactory jf=new JframeFactory();
        InterfaceA pd=jf.getObject("payment");
        pd.x();
        this.dispose();
    }//GEN-LAST:event_PaymentHistButtonActionPerformed

    private void BackButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButton1ActionPerformed
        // TODO add your handling code here:
        Menu m=new Menu();
        m.setVisible(true);
        this.dispose();
        //this.setVisible(true);
    }//GEN-LAST:event_BackButton1ActionPerformed

    private void personalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personalActionPerformed
        // TODO add your handling code here:
        PersonalDetails p=new PersonalDetails();
        p.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_personalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton1;
    private javax.swing.JButton PaymentHistButton;
    private javax.swing.JLabel currentuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton loginhistbutton;
    private javax.swing.JButton personal;
    private javax.swing.JButton reservhistButton;
    // End of variables declaration//GEN-END:variables
}
